
export const COMBAT_OPS = [
    "damage",
    "damage_all",
    "damage_random",
    "damage_split_sequential",
    "damage_follower_or_leader",
    "damage_all_by_allied_golems",
    "damage_split_fixed",
    "damage_random_selected_defense",
    "damage_split_all_enemies",
    "damage_highest_defense",
    "damage_enemy_leader_by_other_allies",
    "damage_self",
    "destroy",
    "destroy_all",
    "destroy_highest",
    "destroy_random",
    "destroy_random_other_allies",
    "destroy_allied_amulets",
    "destroy_allied_amulets_then_damage",
    "destroy_self",
    "destroy_then",
    "destroy_defender_if_damaged",
    "follower_strike_destroy",
    "banish",
    "banish_all_enemy_copies",
    "banish_duplicates_from_deck",
    "banish_random",
    "banish_self",
    "heal_leader",
    "dynamic_heal_leader",
    "set_max_hp",
    "leader_barrier",
    "restore_full_defense_self",
    "restore_self_and_heal_leader",
    "restore_allies"
] as const;
