#!/usr/bin/env tsx
/**
 * Classify cards with both evolve[] and superevolve[] populated.
 * Report only — does NOT modify card JSON (owner review).
 *
 * Run: npm run audit:superevolve-dedup
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ALL_FILE = path.join(__dirname, "../cards/all.json");
const REPORT_FILE = path.join(__dirname, "../docs/audit/super_evolve_dedup_report.md");

type CardJson = {
  id: string;
  name: string;
  set?: string;
  description?: string;
  evolve?: unknown[];
  superevolve?: unknown[];
};

type Bucket = "DUPLICATE" | "INSTEAD" | "DISTINCT";

function normEffects(arr: unknown[] | undefined): string {
  return JSON.stringify(arr ?? []);
}

function hasInstead(text: string): boolean {
  return /super-evolve:[^\n]*\binstead\b/i.test(text);
}

function classify(card: CardJson): Bucket {
  const desc = card.description ?? "";
  if (card.superEvolveReplaces === true || hasInstead(desc)) return "INSTEAD";
  if (normEffects(card.evolve) === normEffects(card.superevolve)) return "DUPLICATE";
  return "DISTINCT";
}

function recommendedAction(bucket: Bucket): string {
  switch (bucket) {
    case "DUPLICATE":
      return "Empty `superevolve[]` (effect lives in `evolve[]`; super fires both, dedup avoids double resolution).";
    case "INSTEAD":
      return "Keep both arrays; engine fires `superevolve[]` only when Super-Evolve line contains \"instead\".";
    case "DISTINCT":
      return "Keep both arrays; engine fires `evolve[]` then `superevolve[]` on super-evolve.";
  }
}

function main() {
  const cards = JSON.parse(fs.readFileSync(ALL_FILE, "utf-8")) as CardJson[];
  const dual = cards.filter(
    (c) =>
      Array.isArray(c.evolve) &&
      c.evolve.length > 0 &&
      Array.isArray(c.superevolve) &&
      c.superevolve.length > 0,
  );

  const byBucket: Record<Bucket, CardJson[]> = {
    DUPLICATE: [],
    INSTEAD: [],
    DISTINCT: [],
  };

  for (const c of dual) {
    byBucket[classify(c)].push(c);
  }

  const lines: string[] = [
    "# Super-Evolve data de-duplication report",
    "",
    "Generated by `npm run audit:superevolve-dedup`. **No card files were modified.**",
    "",
    "Engine rule (§747): on super-evolve, fire `evolve[]` + `superevolve[]` unless Super-Evolve text says **\"instead\"** (then `superevolve[]` only).",
    "",
    "| Bucket | Count | Recommended action |",
    "|--------|------:|--------------------|",
    `| DUPLICATE | ${byBucket.DUPLICATE.length} | Empty \`superevolve[]\` |`,
    `| INSTEAD | ${byBucket.INSTEAD.length} | Keep; engine \"instead\" override |`,
    `| DISTINCT | ${byBucket.DISTINCT.length} | Keep both arrays |`,
    "",
    `Total cards with both arrays populated: **${dual.length}** / ${cards.length}`,
    "",
  ];

  for (const bucket of ["DUPLICATE", "INSTEAD", "DISTINCT"] as Bucket[]) {
    lines.push(`## ${bucket} (${byBucket[bucket].length})`, "");
    lines.push(recommendedAction(bucket), "");
    for (const c of byBucket[bucket].sort((a, b) => a.id.localeCompare(b.id))) {
      const evoLen = c.evolve?.length ?? 0;
      const seLen = c.superevolve?.length ?? 0;
      const superLine =
        (c.description ?? "")
          .split("\n")
          .find((l) => /^super-evolve:/i.test(l.trim()))
          ?.trim() ?? "";
      lines.push(
        `- **${c.id}** ${c.name} (${c.set ?? "?"}) — evolve×${evoLen}, superevolve×${seLen}${superLine ? ` — \`${superLine.slice(0, 80)}\`` : ""}`,
      );
    }
    lines.push("");
  }

  lines.push("## Owner review notes", "");
  lines.push("- Dedup **executed** in `cards/sets/` (80 DUPLICATE emptied, Amorous Drain-only, 5 INSTEAD flagged).");
  lines.push("- **Replicate op** migrated for 16 fanfare-replicate cards.");
  lines.push("- Post-dedup counts above reflect remaining dual-array cards only (INSTEAD + DISTINCT).");
  lines.push("");

  fs.mkdirSync(path.dirname(REPORT_FILE), { recursive: true });
  fs.writeFileSync(REPORT_FILE, lines.join("\n"), "utf-8");

  console.log(`Wrote ${REPORT_FILE}`);
  console.log(
    `DUPLICATE=${byBucket.DUPLICATE.length} INSTEAD=${byBucket.INSTEAD.length} DISTINCT=${byBucket.DISTINCT.length}`,
  );
}

main();
